# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Auto_Test.ui'
#
# Created: Sun Jan 22 15:01:24 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!



▼import sys
import threading

from PyQt4 import QtCore, QtGui

import Main
import Reboot
import SD

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Form(QtGui.QWidget):  #####
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(902, 821)
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 901, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox_reboot = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_reboot.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_reboot.setFont(font)
        self.checkBox_reboot.setObjectName(_fromUtf8("checkBox_reboot"))
        self.horizontalLayout.addWidget(self.checkBox_reboot)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_reboot = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_reboot.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_reboot.setObjectName(_fromUtf8("lineEdit_reboot"))
        self.horizontalLayout.addWidget(self.lineEdit_reboot)
        spacerItem2 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.label_reboot_cycle = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_reboot_cycle.setMaximumSize(QtCore.QSize(30, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_reboot_cycle.setFont(font)
        self.label_reboot_cycle.setObjectName(_fromUtf8("label_reboot_cycle"))
        self.horizontalLayout.addWidget(self.label_reboot_cycle)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.label_reboot_result = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_reboot_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_reboot_result.setFont(font)
        self.label_reboot_result.setObjectName(_fromUtf8("label_reboot_result"))
        self.horizontalLayout.addWidget(self.label_reboot_result)
        spacerItem3 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 901, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setMargin(2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_logo = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_logo.setMaximumSize(QtCore.QSize(100, 60))
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8("Radware-Logo.jpg")))
        self.label_logo.setScaledContents(True)
        self.label_logo.setWordWrap(True)
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout_2.addWidget(self.label_logo)
        spacerItem6 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 770, 621, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_save = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.horizontalLayout_3.addWidget(self.pushButton_save)
        spacerItem7 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pushButton_run = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.horizontalLayout_3.addWidget(self.pushButton_run)
        self.pushButton_cancel = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 50, 901, 51))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_platform = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_platform.setObjectName(_fromUtf8("comboBox_platform"))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_platform)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.comboBox_application = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_application.setObjectName(_fromUtf8("comboBox_application"))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_application)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_COM = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_COM.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_COM.setObjectName(_fromUtf8("lineEdit_COM"))
        self.horizontalLayout_5.addWidget(self.lineEdit_COM)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_MAC = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_MAC.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_MAC.setFont(font)
        self.label_MAC.setObjectName(_fromUtf8("label_MAC"))
        self.horizontalLayout_5.addWidget(self.label_MAC)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_SW = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_SW.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SW.setFont(font)
        self.label_SW.setObjectName(_fromUtf8("label_SW"))
        self.horizontalLayout_5.addWidget(self.label_SW)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_SN = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_SN.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SN.setFont(font)
        self.label_SN.setObjectName(_fromUtf8("label_SN"))
        self.horizontalLayout_5.addWidget(self.label_SN)
        spacerItem13 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(-10, 140, 911, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 911, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(0, 40, 911, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(0, 140, 911, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 150, 901, 51))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.checkBox_sd = QtGui.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_sd.setMaximumSize(QtCore.QSize(120, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_sd.setFont(font)
        self.checkBox_sd.setObjectName(_fromUtf8("checkBox_sd"))
        self.horizontalLayout_4.addWidget(self.checkBox_sd)
        spacerItem15 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_3.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_sd = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_sd.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_sd.setObjectName(_fromUtf8("lineEdit_sd"))
        self.horizontalLayout_4.addWidget(self.lineEdit_sd)
        spacerItem16 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_11.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_sd_cycle = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_sd_cycle.setMaximumSize(QtCore.QSize(30, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sd_cycle.setFont(font)
        self.label_sd_cycle.setObjectName(_fromUtf8("label_sd_cycle"))
        self.horizontalLayout_4.addWidget(self.label_sd_cycle)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_12.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.label_sd_result = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_sd_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sd_result.setFont(font)
        self.label_sd_result.setObjectName(_fromUtf8("label_sd_result"))
        self.horizontalLayout_4.addWidget(self.label_sd_result)
        spacerItem17 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.line_8 = QtGui.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(-10, 240, 911, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 200, 901, 51))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_13.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.lineEdit_sd_sentry = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_sd_sentry.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_sd_sentry.setObjectName(_fromUtf8("lineEdit_sd_sentry"))
        self.horizontalLayout_6.addWidget(self.lineEdit_sd_sentry)
        spacerItem19 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.comboBox_ps_num = QtGui.QComboBox(self.horizontalLayoutWidget_6)
        self.comboBox_ps_num.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_ps_num.setObjectName(_fromUtf8("comboBox_ps_num"))
        self.comboBox_ps_num.addItem(_fromUtf8(""))
        self.comboBox_ps_num.addItem(_fromUtf8(""))
        self.comboBox_ps_num.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_ps_num)
        spacerItem20 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.comboBox_ps_acdc = QtGui.QComboBox(self.horizontalLayoutWidget_6)
        self.comboBox_ps_acdc.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_ps_acdc.setObjectName(_fromUtf8("comboBox_ps_acdc"))
        self.comboBox_ps_acdc.addItem(_fromUtf8(""))
        self.comboBox_ps_acdc.addItem(_fromUtf8(""))
        self.comboBox_ps_acdc.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_ps_acdc)
        spacerItem21 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Auto Test 1-1-2017", None))
        self.checkBox_reboot.setText(_translate("Form", "Reboot Test", None))
        self.label.setText(_translate("Form", "Cycles Number:", None))
        self.label_9.setText(_translate("Form", "Current Cycle:", None))
        self.label_reboot_cycle.setText(_translate("Form", "---", None))
        self.label_10.setText(_translate("Form", "Final Result:", None))
        self.label_reboot_result.setText(_translate("Form", "---", None))
        self.label_2.setText(_translate("Form", "Auto Test 2017", None))
        self.pushButton_save.setText(_translate("Form", "SAVE Results", None))
        self.pushButton_run.setText(_translate("Form", "Run", None))
        self.pushButton_cancel.setText(_translate("Form", "Cancel", None))
        self.label_5.setText(_translate("Form", "Device Info:  ", None))
        self.comboBox_platform.setItemText(0, _translate("Form", "Platform", None))
        self.comboBox_platform.setItemText(1, _translate("Form", "ODS2/3", None))
        self.comboBox_platform.setItemText(2, _translate("Form", "ODSHTQ", None))
        self.comboBox_platform.setItemText(3, _translate("Form", "ODSHTQE", None))
        self.comboBox_platform.setItemText(4, _translate("Form", "ODSLS", None))
        self.comboBox_platform.setItemText(5, _translate("Form", "ODSMR", None))
        self.comboBox_platform.setItemText(6, _translate("Form", "ODSVL", None))
        self.comboBox_platform.setItemText(7, _translate("Form", "ODSVL2", None))
        self.comboBox_application.setItemText(0, _translate("Form", "Application", None))
        self.comboBox_application.setItemText(1, _translate("Form", "Alteon", None))
        self.comboBox_application.setItemText(2, _translate("Form", "DefensePro", None))
        self.comboBox_application.setItemText(3, _translate("Form", "LP", None))
        self.comboBox_application.setItemText(4, _translate("Form", "CID", None))
        self.label_8.setText(_translate("Form", "COM:", None))
        self.label_4.setText(_translate("Form", "MAC:", None))
        self.label_MAC.setText(_translate("Form", "---", None))
        self.label_7.setText(_translate("Form", "SW:", None))
        self.label_SW.setText(_translate("Form", "---", None))
        self.label_6.setText(_translate("Form", "SN:", None))
        self.label_SN.setText(_translate("Form", "---", None))
        self.checkBox_sd.setText(_translate("Form", "ShutDown Test", None))
        self.label_3.setText(_translate("Form", "Cycles Number:", None))
        self.label_11.setText(_translate("Form", "Current Cycle:", None))
        self.label_sd_cycle.setText(_translate("Form", "---", None))
        self.label_12.setText(_translate("Form", "Final Result:", None))
        self.label_sd_result.setText(_translate("Form", "---", None))
        self.label_13.setText(_translate("Form", "Sentry COM:", None))
        self.comboBox_ps_num.setItemText(0, _translate("Form", "  PS 1/2", None))
        self.comboBox_ps_num.setItemText(1, _translate("Form", "1", None))
        self.comboBox_ps_num.setItemText(2, _translate("Form", "2", None))
        self.comboBox_ps_acdc.setItemText(0, _translate("Form", "  PS AC/DC", None))
        self.comboBox_ps_acdc.setItemText(1, _translate("Form", "AC", None))
        self.comboBox_ps_acdc.setItemText(2, _translate("Form", "DC", None))

        ##### coding for buttons

        # self.pushButton_run.clicked.connect(self.run_chosen)
        self.pushButton_run.clicked.connect(self.run_chosen_t)
        self.pushButton_cancel.clicked.connect(self.cancel_chosen)
        self.pushButton_save.clicked.connect(self.save_chosen)
        ##### functions for buttons

    def run_chosen_t(self):
        t = threading.Thread(target=self.run_chosen)
        t.start()

    def run_chosen(self):
        if ex.checkBox_sd.isChecked():
            ser_sent = Main.openSerial_sent(ex)
        ser = Main.openSerial(ex)
        Main.guiInit(ex, True)
        global Device
        Device = Main.device_info(ex, ser)

        ex.label_MAC.setText(_translate("Form", Device[0], None))
        ex.label_SW.setText(_translate("Form", Device[1], None))
        # print ex.comboBox_platform.currentText()
        if ex.checkBox_reboot.isChecked():
            if Reboot.reboot(ser, ex):
                ex.label_reboot_result.setText(_translate("Form", 'PASS', None))
                ex.label_reboot_result.setStyleSheet("QLabel#label_reboot_result {color: green}")
            else:
                ex.label_reboot_result.setText(_translate("Form", 'FAIL', None))
                ex.label_reboot_result.setStyleSheet("QLabel#label_reboot_result {color: red}")
        if ex.checkBox_sd.isChecked():
            if SD.sd(ser, ser_sent, ex):
                ex.label_sd_result.setText(_translate("Form", 'PASS', None))
                ex.label_sd_result.setStyleSheet("QLabel#label_sd_result {color: green}")
            else:
                ex.label_sd_result.setText(_translate("Form", 'FAIL', None))
                ex.label_sd_result.setStyleSheet("QLabel#label_sd_result {color: red}")

        Main.guiInit(ex, False)

    def save_chosen(self):
        Main.save(ex, Device)

    def cancel_chosen(self):
        sys.exit(app.exec_())


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_Form()
    ex.show()
    sys.exit(app.exec_())
