# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Auto_Test.ui'
#
# Created: Sun Jan 22 15:01:24 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

import os
import sys
import threading
import time

from PyQt4 import QtCore, QtGui

import LS
import Main
import Reboot
import SD
import SSL

result_path = 'C:\\Python_projects\\auto_test_py\\results\\'
cap1_path = 'C:\\Python_projects\\auto_test_py\\capture\\capture1.txt'
cap2_path = 'C:\\Python_projects\\auto_test_py\\capture\\capture2.txt'

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Form(QtGui.QWidget):  #####
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(902, 821)
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 901, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox_reboot = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_reboot.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_reboot.setFont(font)
        self.checkBox_reboot.setObjectName(_fromUtf8("checkBox_reboot"))
        self.horizontalLayout.addWidget(self.checkBox_reboot)
        self.checkBox_lspci = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_lspci.setMaximumSize(QtCore.QSize(60, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_lspci.setFont(font)
        self.checkBox_lspci.setObjectName(_fromUtf8("checkBox_lspci"))
        self.horizontalLayout.addWidget(self.checkBox_lspci)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_reboot = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_reboot.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_reboot.setObjectName(_fromUtf8("lineEdit_reboot"))
        self.horizontalLayout.addWidget(self.lineEdit_reboot)
        spacerItem1 = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.label_reboot_cycle = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_reboot_cycle.setMaximumSize(QtCore.QSize(30, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_reboot_cycle.setFont(font)
        self.label_reboot_cycle.setObjectName(_fromUtf8("label_reboot_cycle"))
        self.horizontalLayout.addWidget(self.label_reboot_cycle)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.label_reboot_result = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_reboot_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_reboot_result.setFont(font)
        self.label_reboot_result.setObjectName(_fromUtf8("label_reboot_result"))
        self.horizontalLayout.addWidget(self.label_reboot_result)
        spacerItem2 = QtGui.QSpacerItem(25, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 901, 52))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setMargin(2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_logo = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_logo.setMaximumSize(QtCore.QSize(100, 50))
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8("Radware-Logo.jpg")))
        self.label_logo.setScaledContents(True)
        self.label_logo.setWordWrap(True)
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout_2.addWidget(self.label_logo)
        spacerItem5 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 770, 621, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_save = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.horizontalLayout_3.addWidget(self.pushButton_save)
        spacerItem6 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton_run = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.horizontalLayout_3.addWidget(self.pushButton_run)
        self.pushButton_cancel = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 50, 901, 51))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_platform = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_platform.setObjectName(_fromUtf8("comboBox_platform"))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.comboBox_platform.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_platform)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.comboBox_application = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_application.setObjectName(_fromUtf8("comboBox_application"))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.comboBox_application.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_application)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_COM = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_COM.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_COM.setObjectName(_fromUtf8("lineEdit_COM"))
        self.horizontalLayout_5.addWidget(self.lineEdit_COM)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_MAC = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_MAC.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_MAC.setFont(font)
        self.label_MAC.setObjectName(_fromUtf8("label_MAC"))
        self.horizontalLayout_5.addWidget(self.label_MAC)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_SW = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_SW.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SW.setFont(font)
        self.label_SW.setObjectName(_fromUtf8("label_SW"))
        self.horizontalLayout_5.addWidget(self.label_SW)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_SN = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_SN.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SN.setFont(font)
        self.label_SN.setObjectName(_fromUtf8("label_SN"))
        self.horizontalLayout_5.addWidget(self.label_SN)
        spacerItem12 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(-10, 140, 911, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 911, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(0, 40, 911, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(0, 140, 911, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 150, 901, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem13 = QtGui.QSpacerItem(25, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.checkBox_sd = QtGui.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_sd.setMaximumSize(QtCore.QSize(120, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_sd.setFont(font)
        self.checkBox_sd.setObjectName(_fromUtf8("checkBox_sd"))
        self.horizontalLayout_4.addWidget(self.checkBox_sd)
        spacerItem14 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_3.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_sd = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_sd.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_sd.setObjectName(_fromUtf8("lineEdit_sd"))
        self.horizontalLayout_4.addWidget(self.lineEdit_sd)
        spacerItem15 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_11.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_sd_cycle = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_sd_cycle.setMaximumSize(QtCore.QSize(30, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sd_cycle.setFont(font)
        self.label_sd_cycle.setObjectName(_fromUtf8("label_sd_cycle"))
        self.horizontalLayout_4.addWidget(self.label_sd_cycle)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_12.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.label_sd_result = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_sd_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sd_result.setFont(font)
        self.label_sd_result.setObjectName(_fromUtf8("label_sd_result"))
        self.horizontalLayout_4.addWidget(self.label_sd_result)
        spacerItem16 = QtGui.QSpacerItem(23, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.line_8 = QtGui.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(-10, 300, 911, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 230, 901, 41))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.checkBox_ssl_check = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_ssl_check.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox_ssl_check.setObjectName(_fromUtf8("checkBox_ssl_check"))
        self.horizontalLayout_6.addWidget(self.checkBox_ssl_check)
        self.comboBox_ssl_quant = QtGui.QComboBox(self.horizontalLayoutWidget_6)
        self.comboBox_ssl_quant.setMaximumSize(QtCore.QSize(115, 16777215))
        self.comboBox_ssl_quant.setMaxVisibleItems(65)
        self.comboBox_ssl_quant.setObjectName(_fromUtf8("comboBox_ssl_quant"))
        self.comboBox_ssl_quant.addItem(_fromUtf8(""))
        self.comboBox_ssl_quant.addItem(_fromUtf8(""))
        self.comboBox_ssl_quant.addItem(_fromUtf8(""))
        self.comboBox_ssl_quant.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_ssl_quant)
        spacerItem18 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.comboBox_ssl_type = QtGui.QComboBox(self.horizontalLayoutWidget_6)
        self.comboBox_ssl_type.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_ssl_type.setMaxVisibleItems(65)
        self.comboBox_ssl_type.setObjectName(_fromUtf8("comboBox_ssl_type"))
        self.comboBox_ssl_type.addItem(_fromUtf8(""))
        self.comboBox_ssl_type.addItem(_fromUtf8(""))
        self.comboBox_ssl_type.addItem(_fromUtf8(""))
        self.comboBox_ssl_type.addItem(_fromUtf8(""))
        self.comboBox_ssl_type.setItemText(3, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_ssl_type)
        spacerItem19 = QtGui.QSpacerItem(270, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_14.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.label_card_result = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_card_result.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_card_result.setFont(font)
        self.label_card_result.setObjectName(_fromUtf8("label_card_result"))
        self.horizontalLayout_6.addWidget(self.label_card_result)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 310, 901, 51))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.checkBox_ssl = QtGui.QCheckBox(self.horizontalLayoutWidget_7)
        self.checkBox_ssl.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ssl.setFont(font)
        self.checkBox_ssl.setObjectName(_fromUtf8("checkBox_ssl"))
        self.horizontalLayout_7.addWidget(self.checkBox_ssl)
        self.checkBox_ssl_dis_info = QtGui.QCheckBox(self.horizontalLayoutWidget_7)
        self.checkBox_ssl_dis_info.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ssl_dis_info.setFont(font)
        self.checkBox_ssl_dis_info.setObjectName(_fromUtf8("checkBox_ssl_dis_info"))
        self.horizontalLayout_7.addWidget(self.checkBox_ssl_dis_info)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_18.setMaximumSize(QtCore.QSize(125, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_7.addWidget(self.label_18)
        self.lineEdit_ssl = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_ssl.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_ssl.setObjectName(_fromUtf8("lineEdit_ssl"))
        self.horizontalLayout_7.addWidget(self.lineEdit_ssl)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_16.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.progressBar_ssl = QtGui.QProgressBar(self.horizontalLayoutWidget_7)
        self.progressBar_ssl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.progressBar_ssl.setProperty("value", 24)
        self.progressBar_ssl.setObjectName(_fromUtf8("progressBar_ssl"))
        self.horizontalLayout_7.addWidget(self.progressBar_ssl)
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_17.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.label_ssl_result = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_ssl_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ssl_result.setFont(font)
        self.label_ssl_result.setObjectName(_fromUtf8("label_ssl_result"))
        self.horizontalLayout_7.addWidget(self.label_ssl_result)
        spacerItem22 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 350, 901, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.line.setPalette(palette)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 270, 901, 41))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem23 = QtGui.QSpacerItem(55, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.checkBox_ls = QtGui.QCheckBox(self.horizontalLayoutWidget_8)
        self.checkBox_ls.setMaximumSize(QtCore.QSize(120, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ls.setFont(font)
        self.checkBox_ls.setObjectName(_fromUtf8("checkBox_ls"))
        self.horizontalLayout_8.addWidget(self.checkBox_ls)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_21.setMaximumSize(QtCore.QSize(75, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_8.addWidget(self.label_21)
        self.lineEdit_ls_com = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_ls_com.setMaximumSize(QtCore.QSize(25, 30))
        self.lineEdit_ls_com.setObjectName(_fromUtf8("lineEdit_ls_com"))
        self.horizontalLayout_8.addWidget(self.lineEdit_ls_com)
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_15.setMaximumSize(QtCore.QSize(137, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.lineEdit_ls = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_ls.setMaximumSize(QtCore.QSize(25, 30))
        self.lineEdit_ls.setObjectName(_fromUtf8("lineEdit_ls"))
        self.horizontalLayout_8.addWidget(self.lineEdit_ls)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_19.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.label_ls_cycle = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_ls_cycle.setMaximumSize(QtCore.QSize(30, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ls_cycle.setFont(font)
        self.label_ls_cycle.setObjectName(_fromUtf8("label_ls_cycle"))
        self.horizontalLayout_8.addWidget(self.label_ls_cycle)
        self.label_22 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_22.setMaximumSize(QtCore.QSize(93, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_8.addWidget(self.label_22)
        self.progressBar_ls = QtGui.QProgressBar(self.horizontalLayoutWidget_8)
        self.progressBar_ls.setMaximumSize(QtCore.QSize(80, 16777215))
        self.progressBar_ls.setProperty("value", 24)
        self.progressBar_ls.setObjectName(_fromUtf8("progressBar_ls"))
        self.horizontalLayout_8.addWidget(self.progressBar_ls)
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_20.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_8.addWidget(self.label_20)
        self.label_ls_result = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_ls_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ls_result.setFont(font)
        self.label_ls_result.setObjectName(_fromUtf8("label_ls_result"))
        self.horizontalLayout_8.addWidget(self.label_ls_result)
        spacerItem24 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        self.horizontalLayoutWidget_9 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 710, 901, 61))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem25 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem25)
        self.checkBox_need_reboot = QtGui.QCheckBox(self.horizontalLayoutWidget_9)
        self.checkBox_need_reboot.setMaximumSize(QtCore.QSize(160, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_need_reboot.setFont(font)
        self.checkBox_need_reboot.setObjectName(_fromUtf8("checkBox_need_reboot"))
        self.horizontalLayout_10.addWidget(self.checkBox_need_reboot)
        self.line_9 = QtGui.QFrame(self.horizontalLayoutWidget_9)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_10.addWidget(self.line_9)
        self.checkBox_control_TC = QtGui.QCheckBox(self.horizontalLayoutWidget_9)
        self.checkBox_control_TC.setMaximumSize(QtCore.QSize(160, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_control_TC.setFont(font)
        self.checkBox_control_TC.setObjectName(_fromUtf8("checkBox_control_TC"))
        self.horizontalLayout_10.addWidget(self.checkBox_control_TC)
        self.label_24 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.label_24.setMaximumSize(QtCore.QSize(210, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_10.addWidget(self.label_24)
        self.horizontalSlider_TC = QtGui.QSlider(self.horizontalLayoutWidget_9)
        self.horizontalSlider_TC.setMaximumSize(QtCore.QSize(140, 16777215))
        self.horizontalSlider_TC.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TC.setObjectName(_fromUtf8("horizontalSlider_TC"))
        self.horizontalLayout_10.addWidget(self.horizontalSlider_TC)
        self.label_23 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_10.addWidget(self.label_23)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem26)
        self.label_25 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.label_25.setMaximumSize(QtCore.QSize(210, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_10.addWidget(self.label_25)
        self.lcdNumber_TC = QtGui.QLCDNumber(self.horizontalLayoutWidget_9)
        self.lcdNumber_TC.setMaximumSize(QtCore.QSize(16777215, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lcdNumber_TC.setPalette(palette)
        self.lcdNumber_TC.setStyleSheet(_fromUtf8(""))
        self.lcdNumber_TC.setObjectName(_fromUtf8("lcdNumber_TC"))
        self.horizontalLayout_10.addWidget(self.lcdNumber_TC)
        spacerItem27 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 760, 901, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 700, 901, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayoutWidget_10 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 190, 901, 41))
        self.horizontalLayoutWidget_10.setObjectName(_fromUtf8("horizontalLayoutWidget_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem28 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem28)
        self.comboBox_ps_num = QtGui.QComboBox(self.horizontalLayoutWidget_10)
        self.comboBox_ps_num.setMaximumSize(QtCore.QSize(75, 16777215))
        self.comboBox_ps_num.setObjectName(_fromUtf8("comboBox_ps_num"))
        self.comboBox_ps_num.addItem(_fromUtf8(""))
        self.comboBox_ps_num.addItem(_fromUtf8(""))
        self.comboBox_ps_num.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBox_ps_num)
        spacerItem29 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem29)
        self.comboBox_ps_acdc = QtGui.QComboBox(self.horizontalLayoutWidget_10)
        self.comboBox_ps_acdc.setMaximumSize(QtCore.QSize(95, 16777215))
        self.comboBox_ps_acdc.setObjectName(_fromUtf8("comboBox_ps_acdc"))
        self.comboBox_ps_acdc.addItem(_fromUtf8(""))
        self.comboBox_ps_acdc.addItem(_fromUtf8(""))
        self.comboBox_ps_acdc.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBox_ps_acdc)
        spacerItem30 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem30)
        self.comboBox_pwr_sw = QtGui.QComboBox(self.horizontalLayoutWidget_10)
        self.comboBox_pwr_sw.setMaximumSize(QtCore.QSize(112, 16777215))
        self.comboBox_pwr_sw.setMaxVisibleItems(65)
        self.comboBox_pwr_sw.setObjectName(_fromUtf8("comboBox_pwr_sw"))
        self.comboBox_pwr_sw.addItem(_fromUtf8(""))
        self.comboBox_pwr_sw.addItem(_fromUtf8(""))
        self.comboBox_pwr_sw.addItem(_fromUtf8(""))
        self.comboBox_pwr_sw.addItem(_fromUtf8(""))
        self.comboBox_pwr_sw.setItemText(3, _fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBox_pwr_sw)
        spacerItem31 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem31)
        self.comboBox_tp1 = QtGui.QComboBox(self.horizontalLayoutWidget_10)
        self.comboBox_tp1.setMaximumSize(QtCore.QSize(103, 16777215))
        self.comboBox_tp1.setMaxVisibleItems(65)
        self.comboBox_tp1.setObjectName(_fromUtf8("comboBox_tp1"))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.comboBox_tp1.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBox_tp1)
        spacerItem32 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.comboBox_tp2 = QtGui.QComboBox(self.horizontalLayoutWidget_10)
        self.comboBox_tp2.setMaximumSize(QtCore.QSize(104, 16777215))
        self.comboBox_tp2.setMaxVisibleItems(65)
        self.comboBox_tp2.setObjectName(_fromUtf8("comboBox_tp2"))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.comboBox_tp2.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBox_tp2)
        spacerItem33 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem33)
        self.label_26 = QtGui.QLabel(self.horizontalLayoutWidget_10)
        self.label_26.setMaximumSize(QtCore.QSize(135, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_11.addWidget(self.label_26)
        self.lineEdit_sd_sentry = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_sd_sentry.setMaximumSize(QtCore.QSize(30, 30))
        self.lineEdit_sd_sentry.setObjectName(_fromUtf8("lineEdit_sd_sentry"))
        self.horizontalLayout_11.addWidget(self.lineEdit_sd_sentry)
        spacerItem34 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem34)
        self.label_27 = QtGui.QLabel(self.horizontalLayoutWidget_10)
        self.label_27.setMaximumSize(QtCore.QSize(130, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_11.addWidget(self.label_27)
        self.lineEdit_sd_sentry_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_sd_sentry_2.setMaximumSize(QtCore.QSize(30, 30))
        self.lineEdit_sd_sentry_2.setObjectName(_fromUtf8("lineEdit_sd_sentry_2"))
        self.horizontalLayout_11.addWidget(self.lineEdit_sd_sentry_2)
        spacerItem35 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem35)
        self.line_11 = QtGui.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(0, 700, 901, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(0, 640, 901, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayoutWidget_11 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 650, 911, 61))
        self.horizontalLayoutWidget_11.setObjectName(_fromUtf8("horizontalLayoutWidget_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem36 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem36)
        self.checkBox_Traffic = QtGui.QCheckBox(self.horizontalLayoutWidget_11)
        self.checkBox_Traffic.setMaximumSize(QtCore.QSize(200, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Traffic.setFont(font)
        self.checkBox_Traffic.setObjectName(_fromUtf8("checkBox_Traffic"))
        self.horizontalLayout_12.addWidget(self.checkBox_Traffic)
        self.line_13 = QtGui.QFrame(self.horizontalLayoutWidget_11)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.horizontalLayout_12.addWidget(self.line_13)
        spacerItem37 = QtGui.QSpacerItem(680, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem37)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.horizontalSlider_TC, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.label_23.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Auto Test 1-1-2017", None))
        self.checkBox_reboot.setText(_translate("Form", "Reboot Test", None))
        self.checkBox_lspci.setText(_translate("Form", "LSpci", None))
        self.label.setText(_translate("Form", "Cycles Number:", None))
        self.label_9.setText(_translate("Form", "Current Cycle:", None))
        self.label_reboot_cycle.setText(_translate("Form", "---", None))
        self.label_10.setText(_translate("Form", "Final Result:", None))
        self.label_reboot_result.setText(_translate("Form", "---", None))
        self.label_2.setText(_translate("Form", "Auto Test 2017", None))
        self.pushButton_save.setText(_translate("Form", "SAVE Results", None))
        self.pushButton_run.setText(_translate("Form", "Run", None))
        self.pushButton_cancel.setText(_translate("Form", "Cancel", None))
        self.label_5.setText(_translate("Form", "Device Info:  ", None))
        self.comboBox_platform.setItemText(0, _translate("Form", "Platform", None))
        self.comboBox_platform.setItemText(1, _translate("Form", "ODSHTQE", None))
        self.comboBox_platform.setItemText(2, _translate("Form", "ODSHTQ", None))
        self.comboBox_platform.setItemText(3, _translate("Form", "ODSMR", None))
        self.comboBox_platform.setItemText(4, _translate("Form", "ODSVL2", None))
        self.comboBox_platform.setItemText(5, _translate("Form", "ODSLS", None))
        self.comboBox_platform.setItemText(6, _translate("Form", "ODSVL", None))
        self.comboBox_platform.setItemText(7, _translate("Form", "ODS2/3", None))
        self.comboBox_application.setItemText(0, _translate("Form", "Application", None))
        self.comboBox_application.setItemText(1, _translate("Form", "Alteon", None))
        self.comboBox_application.setItemText(2, _translate("Form", "DefensePro", None))
        self.comboBox_application.setItemText(3, _translate("Form", "AppDirector", None))
        self.comboBox_application.setItemText(4, _translate("Form", "LP", None))
        self.comboBox_application.setItemText(5, _translate("Form", "CID", None))
        self.label_8.setText(_translate("Form", "COM:", None))
        self.label_4.setText(_translate("Form", "MAC:", None))
        self.label_MAC.setText(_translate("Form", "---", None))
        self.label_7.setText(_translate("Form", "SW:", None))
        self.label_SW.setText(_translate("Form", "---", None))
        self.label_6.setText(_translate("Form", "SN:", None))
        self.label_SN.setText(_translate("Form", "---", None))
        self.checkBox_sd.setText(_translate("Form", "ShutDown Test", None))
        self.label_3.setText(_translate("Form", "Cycles Number:", None))
        self.label_11.setText(_translate("Form", "Current Cycle:", None))
        self.label_sd_cycle.setText(_translate("Form", "---", None))
        self.label_12.setText(_translate("Form", "Final Result:", None))
        self.label_sd_result.setText(_translate("Form", "---", None))
        self.checkBox_ssl_check.setText(_translate("Form", "SSL/NLCheck", None))
        self.comboBox_ssl_quant.setItemText(0, _translate("Form", "SSL/NL Quant", None))
        self.comboBox_ssl_quant.setItemText(1, _translate("Form", "1", None))
        self.comboBox_ssl_quant.setItemText(2, _translate("Form", "2", None))
        self.comboBox_ssl_quant.setItemText(3, _translate("Form", "3", None))
        self.comboBox_ssl_type.setItemText(0, _translate("Form", "Card Type", None))
        self.comboBox_ssl_type.setItemText(1, _translate("Form", "Cavium", None))
        self.comboBox_ssl_type.setItemText(2, _translate("Form", "QuickAssist", None))
        self.label_14.setText(_translate("Form", "Final Result:", None))
        self.label_card_result.setText(_translate("Form", "---", None))
        self.checkBox_ssl.setText(_translate("Form", "SSL Test", None))
        self.checkBox_ssl_dis_info.setText(_translate("Form", "Disable info", None))
        self.label_18.setText(_translate("Form", "Time Duration[min]", None))
        self.label_16.setText(_translate("Form", "Test Progress", None))
        self.label_17.setText(_translate("Form", "Final Result:", None))
        self.label_ssl_result.setText(_translate("Form", "---", None))
        self.checkBox_ls.setText(_translate("Form", "Last State Test", None))
        self.label_21.setText(_translate("Form", "PWR Button COM:", None))
        self.label_15.setText(_translate("Form", "Cycles Number(1=8h):", None))
        self.label_19.setText(_translate("Form", "Current Cycle:", None))
        self.label_ls_cycle.setText(_translate("Form", "---", None))
        self.label_22.setText(_translate("Form", "Cycle Progress", None))
        self.label_20.setText(_translate("Form", "Final Result:", None))
        self.label_ls_result.setText(_translate("Form", "---", None))
        self.checkBox_need_reboot.setText(_translate("Form", "Device need reboot", None))
        self.checkBox_control_TC.setText(_translate("Form", "Control Thermal", None))
        self.label_24.setText(_translate("Form", "Thermal Model- 0C [%]", None))
        self.label_23.setText(_translate("Form", "0", None))
        self.label_25.setText(_translate("Form", "Thermal Chamber Temp", None))
        self.comboBox_ps_num.setItemText(0, _translate("Form", "  PS 1/2", None))
        self.comboBox_ps_num.setItemText(1, _translate("Form", "1", None))
        self.comboBox_ps_num.setItemText(2, _translate("Form", "2", None))
        self.comboBox_ps_acdc.setItemText(0, _translate("Form", "  PS AC/DC", None))
        self.comboBox_ps_acdc.setItemText(1, _translate("Form", "AC", None))
        self.comboBox_ps_acdc.setItemText(2, _translate("Form", "DC", None))
        self.comboBox_pwr_sw.setItemText(0, _translate("Form", "Power Switch", None))
        self.comboBox_pwr_sw.setItemText(1, _translate("Form", "Sentry", None))
        self.comboBox_pwr_sw.setItemText(2, _translate("Form", "Power Tower", None))
        self.comboBox_pwr_sw.setItemText(3, _translate("Form", "Horizon", None))
        self.comboBox_tp1.setItemText(0, _translate("Form", "Tower Port 1", None))
        self.comboBox_tp1.setItemText(1, _translate("Form", "aa1", None))
        self.comboBox_tp1.setItemText(2, _translate("Form", "aa2", None))
        self.comboBox_tp1.setItemText(3, _translate("Form", "aa3", None))
        self.comboBox_tp1.setItemText(4, _translate("Form", "aa4", None))
        self.comboBox_tp1.setItemText(5, _translate("Form", "aa5", None))
        self.comboBox_tp1.setItemText(6, _translate("Form", "aa6", None))
        self.comboBox_tp1.setItemText(7, _translate("Form", "aa7", None))
        self.comboBox_tp1.setItemText(8, _translate("Form", "aa8", None))
        self.comboBox_tp1.setItemText(9, _translate("Form", "ab1", None))
        self.comboBox_tp1.setItemText(10, _translate("Form", "ab2", None))
        self.comboBox_tp1.setItemText(11, _translate("Form", "ab3", None))
        self.comboBox_tp1.setItemText(12, _translate("Form", "ab4", None))
        self.comboBox_tp1.setItemText(13, _translate("Form", "ab5", None))
        self.comboBox_tp1.setItemText(14, _translate("Form", "ab6", None))
        self.comboBox_tp1.setItemText(15, _translate("Form", "ab7", None))
        self.comboBox_tp1.setItemText(16, _translate("Form", "ab8", None))
        self.comboBox_tp1.setItemText(17, _translate("Form", "ac1", None))
        self.comboBox_tp1.setItemText(18, _translate("Form", "ac2", None))
        self.comboBox_tp1.setItemText(19, _translate("Form", "ac3", None))
        self.comboBox_tp1.setItemText(20, _translate("Form", "ac4", None))
        self.comboBox_tp1.setItemText(21, _translate("Form", "ac5", None))
        self.comboBox_tp1.setItemText(22, _translate("Form", "ac6", None))
        self.comboBox_tp1.setItemText(23, _translate("Form", "ac7", None))
        self.comboBox_tp1.setItemText(24, _translate("Form", "ac8", None))
        self.comboBox_tp2.setItemText(0, _translate("Form", "Tower Port 2", None))
        self.comboBox_tp2.setItemText(1, _translate("Form", "aa1", None))
        self.comboBox_tp2.setItemText(2, _translate("Form", "aa2", None))
        self.comboBox_tp2.setItemText(3, _translate("Form", "aa3", None))
        self.comboBox_tp2.setItemText(4, _translate("Form", "aa4", None))
        self.comboBox_tp2.setItemText(5, _translate("Form", "aa5", None))
        self.comboBox_tp2.setItemText(6, _translate("Form", "aa6", None))
        self.comboBox_tp2.setItemText(7, _translate("Form", "aa7", None))
        self.comboBox_tp2.setItemText(8, _translate("Form", "aa8", None))
        self.comboBox_tp2.setItemText(9, _translate("Form", "ab1", None))
        self.comboBox_tp2.setItemText(10, _translate("Form", "ab2", None))
        self.comboBox_tp2.setItemText(11, _translate("Form", "ab3", None))
        self.comboBox_tp2.setItemText(12, _translate("Form", "ab4", None))
        self.comboBox_tp2.setItemText(13, _translate("Form", "ab5", None))
        self.comboBox_tp2.setItemText(14, _translate("Form", "ab6", None))
        self.comboBox_tp2.setItemText(15, _translate("Form", "ab7", None))
        self.comboBox_tp2.setItemText(16, _translate("Form", "ab8", None))
        self.comboBox_tp2.setItemText(17, _translate("Form", "ac1", None))
        self.comboBox_tp2.setItemText(18, _translate("Form", "ac2", None))
        self.comboBox_tp2.setItemText(19, _translate("Form", "ac3", None))
        self.comboBox_tp2.setItemText(20, _translate("Form", "ac4", None))
        self.comboBox_tp2.setItemText(21, _translate("Form", "ac5", None))
        self.comboBox_tp2.setItemText(22, _translate("Form", "ac6", None))
        self.comboBox_tp2.setItemText(23, _translate("Form", "ac7", None))
        self.comboBox_tp2.setItemText(24, _translate("Form", "ac8", None))
        self.label_26.setText(_translate("Form", "Sentry/DC Lab1 COM:", None))
        self.label_27.setText(_translate("Form", "DC Lab2 COM:", None))
        self.checkBox_Traffic.setText(_translate("Form", "Traffic Stress [for Alteon]", None))
        ##### coding for buttons
        self.lcdNumber_TC.display(00)
        # self.pushButton_run.clicked.connect(self.run_chosen)
        self.pushButton_run.clicked.connect(self.run_chosen_t)
        self.pushButton_cancel.clicked.connect(self.cancel_chosen)
        self.pushButton_save.clicked.connect(self.save_chosen)
        ##### functions for buttons

    def run_chosen_t(self):
        t = threading.Thread(target=self.run_chosen)
        t.start()

    def read_TC(self):
        # print ser.portstr
        while (1):
            ser_TC.write("PVAR1?\n")
            x = ser_TC.readline()
            ex.lcdNumber_TC.display(x)
            time.sleep(60)

    def run_chosen(self):

        if (ex.checkBox_sd.isChecked() or ex.checkBox_ls.isChecked()):
            ser_sent = Main.openSerial_sent(ex)
        if (ex.comboBox_ps_num.currentText() == '2') and (ex.comboBox_pwr_sw.currentText() == 'Horizon'):
            ser_sent2 = Main.openSerial_sent2(ex)
        if ex.checkBox_ls.isChecked():
            ser_ls = Main.openSerial_ls(ex)
        if ex.checkBox_control_TC.isChecked():
            global ser_TC
            ser_TC = Main.openSerial_TC(ex)
            t1 = threading.Thread(target=self.read_TC)
            t1.start()
        else:
            ser_TC = 1
        ser = Main.openSerial(ex)
        Main.guiInit(ex, True)
        if ex.checkBox_need_reboot.isChecked():
            Main.need_reboot(ex, ser)
        else:
            print "Please Reboot the device"
        global Device
        Device = ['mac', 'sw', 'sn']
        if ex.checkBox_ssl_dis_info.isChecked():
            pass
        else:
            Device = Main.device_info(ex, ser)

        ex.label_MAC.setText(_translate("Form", Device[0], None))
        ex.label_SW.setText(_translate("Form", Device[1], None))
        # print ex.comboBox_platform.currentText()
        if ex.checkBox_reboot.isChecked():
            if Reboot.reboot(ser, ser_TC, ex):
                ex.label_reboot_result.setText(_translate("Form", 'PASS', None))
                ex.label_reboot_result.setStyleSheet("QLabel#label_reboot_result {color: green}")
            else:
                ex.label_reboot_result.setText(_translate("Form", 'FAIL', None))
                ex.label_reboot_result.setStyleSheet("QLabel#label_reboot_result {color: red}")
                os.system('copy ' + cap2_path + ' ' + result_path + 'reboot_fail.txt')

        if ex.checkBox_sd.isChecked():
            # sd_result = SD.sd(ser,ser_sent,ex,card_result)
            if SD.sd(ser, ser_sent, ser_sent2, ser_TC, ex):
                from SD import card_result
                ex.label_sd_result.setText(_translate("Form", 'PASS', None))
                ex.label_sd_result.setStyleSheet("QLabel#label_sd_result {color: green}")
            else:
                from SD import card_result
                ex.label_sd_result.setText(_translate("Form", 'FAIL', None))
                ex.label_sd_result.setStyleSheet("QLabel#label_sd_result {color: red}")
                os.system('copy ' + cap2_path + ' ' + result_path + 'sd_fail.txt')
            if ex.checkBox_ssl_check.isChecked():
                ex.label_card_result.setText(_translate("Form", card_result, None))
                if card_result == 'PASS':
                    ex.label_card_result.setStyleSheet("QLabel#label_card_result {color: green}")
                else:
                    ex.label_card_result.setStyleSheet("QLabel#label_card_result {color: red}")

        if ex.checkBox_ssl.isChecked():
            if SSL.ssl(ser, ex):
                ex.label_ssl_result.setText(_translate("Form", 'PASS', None))
                ex.label_ssl_result.setStyleSheet("QLabel#label_ssl_result {color: green}")
            else:
                ex.label_ssl_result.setText(_translate("Form", 'FAIL', None))
                ex.label_ssl_result.setStyleSheet("QLabel#label_ssl_result {color: red}")

        if ex.checkBox_ls.isChecked():
            if LS.ls(ser, ser_sent, ser_ls, ex):
                from LS import ls_card_result
                print ls_card_result
                ex.label_ls_result.setText(_translate("Form", 'PASS', None))
                ex.label_ls_result.setStyleSheet("QLabel#label_ls_result {color: green}")
            else:
                from LS import ls_card_result
                print ls_card_result
                ex.label_ls_result.setText(_translate("Form", 'FAIL', None))
                ex.label_ls_result.setStyleSheet("QLabel#label_ls_result {color: red}")

        Main.guiInit(ex, False)

    def save_chosen(self):
        if ex.checkBox_ls.isChecked():
            from LS import ls_card_result
        else:
            ls_card_result = 'not tested'

        Main.save(ex, Device, ls_card_result)

    def cancel_chosen(self):
        sys.exit(app.exec_())


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_Form()
    ex.show()
    sys.exit(app.exec_())
