# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Auto_Test.ui'
#
# Created: Thu Jan 19 13:15:32 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

import sys
import threading

from PyQt4 import QtCore, QtGui

import Main
import Reboot

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Form(QtGui.QWidget):  #####
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(902, 821)
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 901, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox_reboot = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_reboot.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_reboot.setFont(font)
        self.checkBox_reboot.setObjectName(_fromUtf8("checkBox_reboot"))
        self.horizontalLayout.addWidget(self.checkBox_reboot)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_reboot = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_reboot.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_reboot.setObjectName(_fromUtf8("lineEdit_reboot"))
        self.horizontalLayout.addWidget(self.lineEdit_reboot)
        spacerItem2 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(90, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.label_reboot_cycle = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_reboot_cycle.setMaximumSize(QtCore.QSize(30, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_reboot_cycle.setFont(font)
        self.label_reboot_cycle.setObjectName(_fromUtf8("label_reboot_cycle"))
        self.horizontalLayout.addWidget(self.label_reboot_cycle)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.label_reboot_result = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_reboot_result.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_reboot_result.setFont(font)
        self.label_reboot_result.setObjectName(_fromUtf8("label_reboot_result"))
        self.horizontalLayout.addWidget(self.label_reboot_result)
        spacerItem3 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 901, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setMargin(2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(560, 770, 321, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_run = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.horizontalLayout_3.addWidget(self.pushButton_run)
        self.pushButton_cancel = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 50, 901, 51))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_5.addWidget(self.comboBox)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.comboBox_2 = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_COM = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_COM.setMaximumSize(QtCore.QSize(40, 30))
        self.lineEdit_COM.setObjectName(_fromUtf8("lineEdit_COM"))
        self.horizontalLayout_5.addWidget(self.lineEdit_COM)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_MAC = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_MAC.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_MAC.setFont(font)
        self.label_MAC.setObjectName(_fromUtf8("label_MAC"))
        self.horizontalLayout_5.addWidget(self.label_MAC)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_SW = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_SW.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SW.setFont(font)
        self.label_SW.setObjectName(_fromUtf8("label_SW"))
        self.horizontalLayout_5.addWidget(self.label_SW)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_SN = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_SN.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SN.setFont(font)
        self.label_SN.setObjectName(_fromUtf8("label_SN"))
        self.horizontalLayout_5.addWidget(self.label_SN)
        spacerItem7 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(0, 140, 911, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 911, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(0, 40, 911, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Auto Test 1-1-2017", None))
        self.checkBox_reboot.setText(_translate("Form", "Reboot Test", None))
        self.label.setText(_translate("Form", "Cycles Number:", None))
        self.label_9.setText(_translate("Form", "Current Cycle:", None))
        self.label_reboot_cycle.setText(_translate("Form", "---", None))
        self.label_10.setText(_translate("Form", "Final Result:", None))
        self.label_reboot_result.setText(_translate("Form", "---", None))
        self.label_2.setText(_translate("Form", "Auto Test 2017", None))
        self.pushButton_run.setText(_translate("Form", "Run", None))
        self.pushButton_cancel.setText(_translate("Form", "Cancel", None))
        self.label_5.setText(_translate("Form", "Device Info:  ", None))
        self.label_8.setText(_translate("Form", "COM:", None))
        self.label_4.setText(_translate("Form", "MAC:", None))
        self.label_MAC.setText(_translate("Form", "---", None))
        self.label_7.setText(_translate("Form", "SW:", None))
        self.label_SW.setText(_translate("Form", "---", None))
        self.label_6.setText(_translate("Form", "SN:", None))
        self.label_SN.setText(_translate("Form", "---", None))

        ##### coding for buttons

        # self.pushButton_run.clicked.connect(self.run_chosen)
        self.pushButton_run.clicked.connect(self.run_chosen_t)
        self.pushButton_cancel.clicked.connect(self.cancel_chosen)
        ##### functions for buttons

    def run_chosen_t(self):
        t = threading.Thread(target=self.run_chosen)
        t.start()

    def run_chosen(self):
        # com_info = ['COM3','9600']
        ser = Main.openSerial(ex)
        Device = Main.device_info(ex, ser)
        ex.label_MAC.setText(_translate("Form", Device[0], None))
        ex.label_SW.setText(_translate("Form", Device[1], None))
        if ex.checkBox_reboot.isChecked():
            if Reboot.reboot(ser, ex):
                ex.label_reboot_result.setText(_translate("Form", 'PASS', None))
            else:
                ex.label_reboot_result.setText(_translate("Form", 'FAIL', None))

    def cancel_chosen(self):
        sys.exit(app.exec_())


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_Form()
    ex.show()
    sys.exit(app.exec_())
